const express = require('express');
var morgan = require('morgan');
const app = express();
const port = 4000;
const router = require('./routes');
app.use(morgan('dev'));
app.use('/usm', router);
app.use(express.static('public'));
app.get('/', (req, res) => res.send('Hello World!'));
app.listen(port, () => console.log(`Example app listening on port ${port}`));